version: '2'
services:
    uashield:
      build: .
      restart: always
      container_name: uashield
      environment:
        WORKERS: '256'
        USEPROXY: 'false'
      networks:
        - shield

networks:
  shield:
    driver: bridge
