---
##@ref https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#variables-and-vaults

#Docker

docker_version: 5.0.3
docker_users: []

#Uashield

uashield_git_url: "https://github.com/opengs/uashield"
uashield_work_dir: /root/uashield/
uashield_threads: 128
uashield_proxy: false
