version: '2'
services:
    repeater:
        image: ghcr.io/opengs/uashield:go-experimental
        restart: always
        environment:
            - ONLYOK=true
            - USEPROXY=true
            - TIMEOUT=5000
            - WORKERS=128
            - REPEATTARGET=true
            - DISGUISEASBOTPERCENTAGE=1
            - REPEATERSPAWNNEWWORKERS=true
            - REPEATERSPAWNNEWWORKERSCOUNT=512
            - REPEATSLEEPBEFORE=50
            - MAXREPEATING=10240
            - TARGETONLY200=false