---
- name: Clone uashield repo
  git:
    repo: "{{uashield_git_url}}"
    dest: "{{uashield_work_dir}}"
    accept_hostkey: true
    force: true
    version: "master"

- name: Stop all containers
  shell: "docker-compose down"
  args:
    chdir: "{{uashield_work_dir}}"

- name: Remove old uashield images
  shell: "docker rmi -f uashield"

- name: Run uashield
  shell: "docker-compose up -d"
  args:
    chdir: "{{uashield_work_dir}}"

- name: Check docker started
  shell: "docker ps"
  args:
    chdir: "{{uashield_work_dir}}"
  register: output

- ansible.builtin.debug:
        var: output

- name: Chmod bash script for image update
  shell: "chmod +x /root/uashield/tools/ansible/update-build.sh"

- name: Remove /root/cronjob file if exists
  shell: "rm /root/cronjob"
  ignore_errors: yes

- name: Add every 30 minutes image update as a cronjob
  shell: "sudo echo '*/30 * * * * /root/uashield/tools/ansible/update-build.sh' >> /root/cronjob"

- name: Add every reboot image update as a cronjob
  shell: "sudo echo '@reboot /root/uashield/tools/ansible/update-build.sh' >> /root/cronjob && crontab /root/cronjob"
